// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Database } from './types';

const SUPABASE_URL = "https://bugwqaacemblvuurzgke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1Z3dxYWFjZW1ibHZ1dXJ6Z2tlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0OTEwMDAsImV4cCI6MjA3MDA2NzAwMH0.jofgnMn-u3bgGma8-lynPLo_xvU5MJ40WODf8f_tkzg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});